name: Cypress Tests

on: [push]

jobs:
  cypress-tests:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        spec: 
          - 'cypress/e2e/addCart.cy.js'
          - 'cypress/e2e/checkout.cy.js'
          - 'cypress/e2e/login.cy.js'
          - 'cypress/e2e/searchProducts.cy.js'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install
          npm install mochawesome mochawesome-merge mochawesome-report-generator --save-dev

      - name: Run Cypress Tests in Headed Mode
        uses: cypress-io/github-action@v6
        with:
          spec: ${{ matrix.spec }}
          record: false
          browser: chrome
          start: npx cypress run --headed

      - name: Merge and Generate Report
        if: ${{ always() }}
        run: |
          npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json
          npx mochawesome-report-generator generate cypress/reports/report.json
        continue-on-error: true
